* metaType
  A Chrome plugin that processes normal sentences into expanded text going rightwards and downwards.

** Example:

   If we process the following input using the extension:

#+BEGIN_SRC
META
#+END_SRC

   It becomes:

#+BEGIN_SRC
M E T A
E
T
A
#+END_SRC

** How to install:

   1) =git clone= this repository into a directory.
   2) Launch Chrome.
   3) Type =chrome://extensions/= into the awesome bar.
   4) Check the =Developer mode= checkbox on the top right.
   5) Click =Load unpacked extension...=.
   6) Select the cloned directory and click =OK=.
   7) Check the =Allow in incognito= checkbox for metaType if you're into that.
   8) Scroll to the bottom and click =Keyboard shortcuts=.
   9) Set a shortcut for =Activate the extension= under =metaType= (I use =Ctrl + Shift + Y= ) and click =OK=.
   10) Enjoy B)

** How to metaType:

   1) Press your shortcut key combination (for me it is =Ctrl + Shift + Y= ).
   2) Type or paste any text that you want to meta-ize and the press =Enter= .
   3) Hit =Ctrl + v= into any textfield.
   4) Enjoy B)

